-- ═══════════════════════════════════════════════════════════════════════════════
-- YouTube Metadata Documentation
-- Added: 2025-01-XX
-- Purpose: Document YouTube metadata storage structure
-- ═══════════════════════════════════════════════════════════════════════════════

-- NOTE: YouTube metadata is stored in the existing messages.media JSON field
-- No schema changes needed - this migration is for documentation only
--
-- Structure in messages.media JSON:
-- {
--     "youtube_videos": [
--         {
--             "url": "https://www.youtube.com/watch?v=VIDEO_ID",
--             "video_id": "VIDEO_ID",
--             "title": "Video Title (if extracted)",
--             "duration": 123,  -- seconds (if available)
--             "processed_at": 1234567890  -- timestamp
--         }
--     ],
--     ... other media items ...
-- }
--
-- The media field can contain multiple media types:
-- - Regular media (photos, videos, audio) as inline_data
-- - YouTube URLs as file_uri references
-- - Other file references

-- No actual SQL changes - this file documents the structure
-- This is a no-op migration for documentation purposes
SELECT 1;
